### ISSUE TITLE
update isMongo facet to sort by checked:desc, count:desc

### ISSUE THREAD

**Issue by doug-patterson** [smartprocure/contexture-mongo#82]
Right now checked values in a facet don't get any special treatment, and so don't show up at the top of the facet list unless the list is long enough to reach the position where they'd be if they weren't checked. This is a regression from something.

Need to add to https://github.com/smartprocure/contexture-mongo/blob/master/src/example-types/facet.js#L17 roughly like this:

```js
  { $addFields: { isSelected: <is in node.values> } },
  { $sort: { isSelected: -1, count: 1 } } 
```

to produce a sort by checked-ness first

**Comment by daedalus28** [comment]
in contexture-elasticsearch, we make a second search call to get the counts for any missing values:

https://github.com/smartprocure/contexture-elasticsearch/blob/master/src/example-types/facet.js#L116-L145

We might want to do something similar here. I don't think we can do it in one request because you should still get whatever the count # of options in addition to whatever is checked.

**Comment by doug-patterson** [comment]
@daedalus28 ok, yep, looks like we need to do the same here. will update
